[[headers]]
    for = "/*"
    [headers.values]
        Cache-Control = "max-age=604800"

        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''
