[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''
        
        Permissions-Policy= '''
            autoplay=(),
        '''
