[[headers]]
    for = "/*"
    [headers.values]
        Cache-Control = "max-age=604800"
        Content-Encoding = "gzip"
        Accept-Encoding = "gzip"

        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''
        
        Permissions-Policy= '''
            autoplay=(),
        '''
